Validate PR title before proceeding
Validates PR title starts with a valid format of Jira issue followed by
a colon (e.g. WA-42:) and exits with failure if not.

diff --git a/.github/workflows/update-jira-issue.yml b/.github/workflows/update-jira-issue.yml
--- a/.github/workflows/update-jira-issue.yml
+++ b/.github/workflows/update-jira-issue.yml
@@ -95,6 +95,18 @@ jobs:
     if: github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.merged == true # Dependabot is NOT the author & PR is merged
     runs-on: ubuntu-latest
     steps:
+      - name: Validate pull request title
+        id: validate_pr_title
+        run: |
+          if [[ "${{ github.event.pull_request.title }}" =~ ^[A-Z]+-[0-9]+: ]]; then
+            echo "PR title is valid"
+          else
+            echo "Invalid PR title format. It should start with a Jira issue key."
+            echo "👇👇👇👇👇 MANUAL FIX NEEDED 👇👇👇👇👇"
+            echo "Unfortunately, fixing the PR title and re-running the action won't work, so you'll need to manually update the Jira issue."
+            exit 1
+          fi
+
       - name: Log in to Jira
         uses: atlassian/gajira-login@v3
         env:
